spring:
  datasource:
    url: jdbc:sqlserver://dbserver1212121.database.windows.net:1433;database=Test-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: abhishektest
    password: test123@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


